Enhancement in install script to handle out of space errors
LIS/lis-rpm-build-pipeline pull request #33
Opened 2019-04-09 12:37 UTC by DivyaJyothiKasam

2019-04-10 12:10 UTC, DivyaJyothiKasam commented
Logs for RHEL73 with mlnx:
[root@rhel73 LISISO]# df -h
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  109M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  986M   29M  98% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel73 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 140MB in root partition

[root@rhel73 LISISO]# df -Ph
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  108M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  986M   29M  98% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel73 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 140MB in root partition

[root@rhel73 LISISO]# df -Ph
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  108M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  983M   32M  97% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel73 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 140MB in root partition


[root@rhel73 LISISO]# df -Ph
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/rhel_rhel73-root   40G   40G  145M 100% /
devtmpfs                      320M     0  320M   0% /dev
tmpfs                         332M     0  332M   0% /dev/shm
tmpfs                         332M  5.0M  327M   2% /run
tmpfs                         332M     0  332M   0% /sys/fs/cgroup
/dev/sda1                    1014M  975M   40M  97% /boot
/dev/mapper/rhel_rhel73-home   20G  1.2G   19G   7% /home
tmpfs                          67M     0   67M   0% /run/user/1000
tmpfs                          67M     0   67M   0% /run/user/0
[root@rhel73 LISISO]# ./install.sh
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS73
RPM's are available
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0-20190404 ########################################
microsoft-hyper-v-4.3.0-20190404      ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0-2019########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.

2019-04-10 12:11 UTC, DivyaJyothiKasam commented
Logs for RHEL75 without mlx:

[root@rhel75 LISISO]# df -h
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  109M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  986M   29M  98% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel75 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 40MB in root partition

[root@rhel75 LISISO]# df -Ph
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  108M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  986M   29M  98% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel75 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 40MB in root partition



[root@rhel75 LISISO]# df -Ph
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   41G   41G  108M 100% /
devtmpfs               322M     0  322M   0% /dev
tmpfs                  333M     0  333M   0% /dev/shm
tmpfs                  333M  4.6M  328M   2% /run
tmpfs                  333M     0  333M   0% /sys/fs/cgroup
/dev/sda1             1014M  983M   32M  97% /boot
/dev/mapper/rhel-home   20G  1.2G   19G   6% /home
tmpfs                   67M     0   67M   0% /run/user/1000
[root@rhel75 LISISO]# ./install.sh
To install RPM you need to have minimum 30MB in boot and 40MB in root partition


[root@rhel75 LISISO]# df -Ph
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/rhel_rhel75-root   40G   40G  145M 100% /
devtmpfs                      320M     0  320M   0% /dev
tmpfs                         332M     0  332M   0% /dev/shm
tmpfs                         332M  5.0M  327M   2% /run
tmpfs                         332M     0  332M   0% /sys/fs/cgroup
/dev/sda1                    1014M  975M   40M  97% /boot
/dev/mapper/rhel_rhel75-home   20G  1.2G   19G   7% /home
tmpfs                          67M     0   67M   0% /run/user/1000
tmpfs                          67M     0   67M   0% /run/user/0
[root@rhel75 LISISO]# ./install.sh
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS75
RPM's are available
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0-20190404 ########################################
microsoft-hyper-v-4.3.0-20190404      ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0-2019########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.

2019-04-16 23:12 UTC, johnsongeorge-w commented
@DivyaJyothiKasam : Define a variable to hold the MINIMUM space for boot partition and partition holding lib_modules and use it for comparison.

2019-04-17 13:00 UTC, DivyaJyothiKasam commented
> @DivyaJyothiKasam : Define a variable to hold the MINIMUM space for boot partition and partition holding lib_modules and use it for comparison.

Added a variable

2019-05-06 12:06 UTC, DivyaJyothiKasam commented
Linux Script Logs:
########CLEAN VM#################
[root@c73 LISISO]# ./install.sh
rpm_install_size 65.7301
existing_initramfs_size 20
min_initramfs 20
This is cleanup install
same_partition_minimum_req_disk 235.7301
diff_partition_minimum_req_disk_boot 40
diff_partition_minimum_req_disk_module 215.7301
in 73 same_partition_minimum_req_disk 285.7301
diff_partition_minimum_req_disk_module 265.7301
boot and modules do not share the same partition.
/dev/sda1 Required size: 40 MB. Available: 436
/dev/sda2 Required size: 265.7301 MB. Available: 27828
Removing Hyper-V daemons
Removing the hypervkvpd package
Removing the hyperv-daemons-license package
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS73
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.1-20190412 ########################################
microsoft-hyper-v-4.3.1-20190412      ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.1-2019########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.

################UNINSTALL####################
[root@c73 LISISO]# ./uninstall.sh
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.
Uninstalled Linux Integration Services for Microsoft Hyper-V. Please reboot your system.


################UPGRADE##########################
rpm_install_size 65.7301
existing_initramfs_size 18
min_initramfs 0
This is re-install/upgrade
same_partition_minimum_req_disk 215.7301
diff_partition_minimum_req_disk_boot 20
diff_partition_minimum_req_disk_module 215.7301
in 73 same_partition_minimum_req_disk 265.7301
diff_partition_minimum_req_disk_module 265.7301
boot and modules do not share the same partition.
/dev/sda1 Required size: 20 MB. Available: 421
/dev/sda2 Required size: 265.7301 MB. Available: 27703
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS73
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.1-20190412 ########################################
microsoft-hyper-v-4.3.1-20190412      ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.1-2019########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.

2019-05-06 13:25 UTC, prashantmhetar commented on LISISO/install.sh
> +echo "rpm_install_size $rpm_install_size"
These debug prints need to be redirected to log file

2019-05-07 07:34 UTC, johnsongeorge-w requested changes
Check the review comments and address accordingly.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +mlx_driver_size=50
Is this required ? when we are quering the size of RPM which includes the mlx driver too.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +        if [ "$distro_version" == 73 ] || [ "$distro_version" == 74 ]; then
Is this required ? when we are quering the size of RPM which includes the mlx driver too.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +        if [ "$distro_version" == 73 ] || [ "$distro_version" == 74 ]; then
Is this required ? when we are quering the size of RPM which includes the mlx driver too.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +fi
This should be implemented as a function and it should be just called before install

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +                echo "ERROR: Please make sure that you have sufficient disk space available in '$boot_partition_name'."
Looking for the following error message.

Not sufficient space to start LIS Installation.
                Partition containing /boot                       : Minimum Required Space (XX MB)      Current Space (YY MB)
                Partition containing lib_modules             : Minimum Required Space (ZZ MB)      Current Space (AA MB)

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +	echo "$boot_partition_name Required size: $diff_partition_minimum_req_disk_boot MB. Available: $current_boot_partition_space"
This should only be printed when there is not sufficient space.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +        echo  "boot and modules share the same partition."
These are internal and need not be printed for user.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +rpm_install_size=`rpm -qpi ${distro_package_name}${distro_version}/*hyper-v*x86_64.rpm | grep "Size" | awk '{ total += $3; print }; END { print total /1024/1024}' | tail -1`
As commented below. If this statement is inside a function and it is called just before install then distro_package_name and distro_version is not required.

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +temp_disk_usage_diff_partition_modules_clean_install=150
Why this is required ?

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +temp_disk_usage_diff_partition_boot_clean_install=20
Why this is required ?

2019-05-07 07:34 UTC, johnsongeorge-w commented on LISISO/install.sh
> +existing_initramfs_size=`ls -lh /boot/"initramfs-$(uname -r).img" | awk '{print $5}' | tr -d "M"`
What will happen if the ramdisk file size is shown in KB or GB ? Dont use -h option for ls and get the size in bytes.

2019-05-14 11:49 UTC, closed without merging